### ISSUE TITLE
fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/json-key-validate#9]
- Delete package-lock.json
- Run `npm install`
- Commit the updated package-lock.json
- Create pull request

**Comment by aws-4** [comment]
Hi @arshadkazmi42!  I'm a new contributor, and this looks like an excellent first issue to work on.  If you're still looking for someone to do this, I'd love to be assigned, and I'll try to have it finished a week after assignment at the latest.  Thanks!

**Comment by arshadkazmi42** [comment]
> Hi @arshadkazmi42!  I'm a new contributor, and this looks like an excellent first issue to work on.  If you're still looking for someone to do this, I'd love to be assigned, and I'll try to have it finished a week after assignment at the latest.  Thanks!

Sure. Go for it.
